name: wesite CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        cd client
        npm i
        npm run build
        npm fund
        npm audit fix
        npm audit fix --force
        npx browserslist@latest --update-db
        npm install urix
        npm install resolve-url
        bower install resolve-url
        component install lydell/resolve-url

